In [15]:
using DataFrames
using CSV

┌ Info: Recompiling stale cache file C:\Users\WorkStation\.juliapro\JuliaPro_v1.2.0-2\compiled\v1.2\CSV\HHBkp.ji for CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b]
└ @ Base loading.jl:1240


In [281]:
#Loading Data
using CSV
data = CSV.read("bank-additional-full.csv"; copycols=true)

41188×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 3     │ 37    │ services    │ married  │ high.school         │ no      │
│ 4     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 5     │ 56    │ services    │ married  │ high.school         │ no      │
│ 6     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 7     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 8     │ 41    │ blue-collar │ married  │ unknown             │ unknown │
│ 9     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 10    │ 25    │ services    │ single   │ high.school         │ no      │
⋮
│ 41178 │ 57    │ retired     │ married  │ professional.course │ no      │
│ 41179 │ 62    │ retired     │ married  │ university.degree   │ no      │
│ 41180 │ 64    │ retired     │ divorced │ professional.course │ no      │
│ 41181 │ 36    │ admin.      │ married  │ university.degree   │ no      │
│ 41182 │ 37    │ admin.      │ married  │ university.degree   │ no      │
│ 41183 │ 29    │ unemployed  │ single   │ basic.4y            │ no      │
│ 41184 │ 73    │ retired     │ married  │ professional.course │ no      │
│ 41185 │ 46    │ blue-collar │ married  │ professional.course │ no      │
│ 41186 │ 56    │ retired     │ married  │ university.degree   │ no      │
│ 41187 │ 44    │ technician  │ married  │ professional.course │ no      │
│ 41188 │ 74    │ retired     │ married  │ professional.course │ no      │

In [282]:
#checking all the columns
names(data)

21-element Array{Symbol,1}:
 :age                    
 :job                    
 :marital                
 :education              
 :default                
 :housing                
 :loan                   
 :contact                
 :month                  
 :day_of_week            
 :duration               
 :campaign               
 :pdays                  
 :previous               
 :poutcome               
 Symbol("emp.var.rate")  
 Symbol("cons.price.idx")
 Symbol("cons.conf.idx") 
 :euribor3m              
 Symbol("nr.employed")   
 :y                      

In [283]:
show(data)

41188×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 3     │ 37    │ services    │ married  │ high.school         │ no      │
│ 4     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 5     │ 56    │ services    │ married  │ high.school         │ no      │
│ 6     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 7     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 8     │ 41    │ blue-collar │ married  │ unknown             │ unknown │
│ 9     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 10    │ 25    │ services    │ single   │ high.s

In [285]:
#filter out the unkown data for jobs
filter!(row -> row[:job] != ("unknown"), data);

In [286]:
show(data)

40858×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 3     │ 37    │ services    │ married  │ high.school         │ no      │
│ 4     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 5     │ 56    │ services    │ married  │ high.school         │ no      │
│ 6     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 7     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 8     │ 41    │ blue-collar │ married  │ unknown             │ unknown │
│ 9     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 10    │ 25    │ services    │ single   │ high.s

In [287]:
#filter out unkowns for marital
filter!(row -> row[:marital] != ("unknown"), data);

In [50]:
show(data)

40786×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 6     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 7     │ 41    │ blue-collar │ married  │ unknown             │ unknown │
│ 8     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 9     │ 25    │ services    │ single   │ high.school         │ no      │
│ 10    │ 41    │ blue-collar │ married  │ unknow

In [290]:
#filter out education unknown
filter!(row -> row[:education] != ("unknown"), data);

In [291]:
show(data)

39191×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 3     │ 37    │ services    │ married  │ high.school         │ no      │
│ 4     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 5     │ 56    │ services    │ married  │ high.school         │ no      │
│ 6     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 7     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 8     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 9     │ 25    │ services    │ single   │ high.school         │ no      │
│ 10    │ 25    │ services    │ single   │ high.s

In [289]:
eachcol(filter!(row -> row[:marital] != ("unknown"), data);)

39191×21 DataFrameColumns (with names=false). Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 57    │ services    │ married  │ high.school         │ unknown │
│ 3     │ 37    │ services    │ married  │ high.school         │ no      │
│ 4     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 5     │ 56    │ services    │ married  │ high.school         │ no      │
│ 6     │ 45    │ services    │ married  │ basic.9y            │ unknown │
│ 7     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 8     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 9     │ 25    │ services    │ single   │ high.school         │ no      │
│ 10    │ 25    │ services    │ single   │ high.school         │ no      │
⋮
│ 39181 │ 57    │ retired     │ married  │ professional.course │ no      │
│ 39182 │ 62    │ retired     │ married  │ university.degree   │ no      │
│ 39183 │ 64    │ retired     │ divorced │ professional.course │ no      │
│ 39184 │ 36    │ admin.      │ married  │ university.degree   │ no      │
│ 39185 │ 37    │ admin.      │ married  │ university.degree   │ no      │
│ 39186 │ 29    │ unemployed  │ single   │ basic.4y            │ no      │
│ 39187 │ 73    │ retired     │ married  │ professional.course │ no      │
│ 39188 │ 46    │ blue-collar │ married  │ professional.course │ no      │
│ 39189 │ 56    │ retired     │ married  │ university.degree   │ no      │
│ 39190 │ 44    │ technician  │ married  │ professional.course │ no      │
│ 39191 │ 74    │ retired     │ married  │ professional.course │ no      │

In [292]:
#filter out unkowns for defualt
filter!(row -> row[:default] != ("unknown"), data);

In [293]:
show(data)

31227×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.

In [294]:
tail(data)

┌ Warning: `tail(df::AbstractDataFrame)` is deprecated, use `last(df, 6)` instead.
│   caller = top-level scope at In[294]:1
└ @ Core In[294]:1


6×21 DataFrame. Omitted printing of 16 columns
│ Row │ age   │ job         │ marital │ education           │ default │
│     │ Int64 │ String      │ String  │ String              │ String  │
├─────┼───────┼─────────────┼─────────┼─────────────────────┼─────────┤
│ 1   │ 29    │ unemployed  │ single  │ basic.4y            │ no      │
│ 2   │ 73    │ retired     │ married │ professional.course │ no      │
│ 3   │ 46    │ blue-collar │ married │ professional.course │ no      │
│ 4   │ 56    │ retired     │ married │ university.degree   │ no      │
│ 5   │ 44    │ technician  │ married │ professional.course │ no      │
│ 6   │ 74    │ retired     │ married │ professional.course │ no      │

In [295]:
show(data)

31227×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.

In [296]:
#filter out unknowns for loan
filter!(row -> row[:loan] != ("unknown"), data);

In [297]:
show(data)

30488×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.

In [298]:
filter!(row -> row[:contact] != ("unknown"), data);

In [299]:
show(data)

30488×21 DataFrame. Omitted printing of 16 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.

In [300]:
filter!(row -> row[:month] != ("unknown"), data);

In [301]:
filter!(row -> row[:day_of_week] != ("unknown"), data);

In [303]:
filter!(row -> row[Symbol("emp.var.rate")] != ("nonexistent"), data);

In [83]:
#check column types
[eltype(col) for col = eachcol(data)]

21-element Array{DataType,1}:
 Int64  
 String 
 String 
 String 
 String 
 String 
 String 
 String 
 String 
 String 
 Int64  
 Int64  
 Int64  
 Int64  
 String 
 Float64
 Float64
 Float64
 Float64
 Float64
 String 

In [305]:
#remove column with too much nonexixtent data
select!(data, Not([Symbol("emp.var.rate")]))

30488×20 DataFrame. Omitted printing of 15 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.4y            │ no      │
⋮
│ 30478 │ 57    │ retired     │ married  │ professional.course │ no      │
│ 30479 │ 62    │ retired     │ married  │ university.degree   │ no      │
│ 30480 │ 64    │ retired     │ divorced │ professional.course │ no      │
│ 30481 │ 36    │ admin.      │ married  │ university.degree   │ no      │
│ 30482 │ 37    │ admin.      │ married  │ university.degree   │ no      │
│ 30483 │ 29    │ unemployed  │ single   │ basic.4y            │ no      │
│ 30484 │ 73    │ retired     │ married  │ professional.course │ no      │
│ 30485 │ 46    │ blue-collar │ married  │ professional.course │ no      │
│ 30486 │ 56    │ retired     │ married  │ university.degree   │ no      │
│ 30487 │ 44    │ technician  │ married  │ professional.course │ no      │
│ 30488 │ 74    │ retired     │ married  │ professional.course │ no      │

In [306]:
using StatsModels

In [110]:
#enable the flux framework
using Pkg
Pkg.add("Flux")
using Flux

 Resolving package versions...
 Installed Flux ───────── v0.10.3
 Installed CUDAapi ────── v2.1.0
 Installed GPUArrays ──── v2.0.1
 Installed CUDAdrv ────── v5.1.0
 Installed LLVM ───────── v1.4.0
 Installed CUDAnative ─── v2.7.0
 Installed Adapt ──────── v1.0.1
 Installed CEnum ──────── v0.2.0
 Installed TimerOutputs ─ v0.5.5
 Installed CuArrays ───── v1.6.0
  Updating `C:\Users\WorkStation\.juliapro\JuliaPro_v1.2.0-2\environments\v1.2\Project.toml`
  [587475ba] + Flux v0.10.3
  Updating `C:\Users\WorkStation\.juliapro\JuliaPro_v1.2.0-2\environments\v1.2\Manifest.toml`
  [79e6a3ab] + Adapt v1.0.1
  [fa961155] + CEnum v0.2.0
  [3895d2a7] + CUDAapi v2.1.0
  [c5f51814] + CUDAdrv v5.1.0
  [be33ccc6] + CUDAnative v2.7.0
  [3da002f7] ↓ ColorTypes v0.10.3 ⇒ v0.9.1
  [5ae59095] ↓ Colors v0.12.0 ⇒ v0.11.2
  [3a865a2d] + CuArrays v1.6.0
  [587475ba] + Flux v0.10.3
  [0c68f7d7] + GPUArrays v2.0.1
  [4d00f742] ↑ GeometryTypes v0.7.6 ⇒ v0.7.10
  [929cbde3] + LLVM v1.4.0
  [a759f4b9] + TimerOutputs

┌ Info: Precompiling Flux [587475ba-b771-5e3f-ad9e-33799f191a9c]
└ @ Base loading.jl:1242
┌ Warning: Module DataStructures with build ID 769556382972200 is missing from the cache.
│ This may mean DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1000
┌ Warning: Module DataStructures with build ID 769556382972200 is missing from the cache.
│ This may mean DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1000
┌ Warning: Module DataStructures with build ID 769556382972200 is missing from the cache.
│ This may mean DataStructures [864edb3b-99cc-5e75-8d2d-829cb0a9cfe8] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1000
┌ Warning: Module DataStructures with build ID 769556382972200 is missing from the cache.
│ This may mean DataStructures [864edb3b-99cc-5e75-8

In [135]:
using DataFrames: CategoricalArrays

In [307]:
#assinged the data to variable for insurance 
datatest = data

30488×20 DataFrame. Omitted printing of 15 columns
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.4y            │ no      │
⋮
│ 30478 │ 57    │ retired     │ married  │ professional.course │ no      │
│ 30479 │ 62    │ retired     │ married  │ university.degree   │ no      │
│ 30480 │ 64    │ retired     │ divorced │ professional.course │ no      │
│ 30481 │ 36    │ admin.      │ married  │ university.degree   │ no      │
│ 30482 │ 37    │ admin.      │ married  │ university.degree   │ no      │
│ 30483 │ 29    │ unemployed  │ single   │ basic.4y            │ no      │
│ 30484 │ 73    │ retired     │ married  │ professional.course │ no      │
│ 30485 │ 46    │ blue-collar │ married  │ professional.course │ no      │
│ 30486 │ 56    │ retired     │ married  │ university.degree   │ no      │
│ 30487 │ 44    │ technician  │ married  │ professional.course │ no      │
│ 30488 │ 74    │ retired     │ married  │ professional.course │ no      │

In [309]:
#changing the target variable to binary
datatest.y = replace(datatest.y, "yes" => 1)

30488-element PooledArrays.PooledArray{Any,UInt32,1,Array{UInt32,1}}:
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
  "no"
 ⋮    
  "no"
  "no"
 1    
  "no"
  "no"
 1    
  "no"
 1    
  "no"
  "no"
 1    
  "no"

In [310]:
datatest.y = replace(datatest.y, "no" => 0)

30488-element PooledArrays.PooledArray{Any,UInt32,1,Array{UInt32,1}}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 1
 0
 0
 1
 0
 1
 0
 0
 1
 0

In [311]:
show(datatest, allrows=false, allcols=true)

30488×20 DataFrame
│ Row   │ age   │ job         │ marital  │ education           │ default │
│       │ Int64 │ String      │ String   │ String              │ String  │
├───────┼───────┼─────────────┼──────────┼─────────────────────┼─────────┤
│ 1     │ 56    │ housemaid   │ married  │ basic.4y            │ no      │
│ 2     │ 37    │ services    │ married  │ high.school         │ no      │
│ 3     │ 40    │ admin.      │ married  │ basic.6y            │ no      │
│ 4     │ 56    │ services    │ married  │ high.school         │ no      │
│ 5     │ 59    │ admin.      │ married  │ professional.course │ no      │
│ 6     │ 24    │ technician  │ single   │ professional.course │ no      │
│ 7     │ 25    │ services    │ single   │ high.school         │ no      │
│ 8     │ 25    │ services    │ single   │ high.school         │ no      │
│ 9     │ 29    │ blue-collar │ single   │ high.school         │ no      │
│ 10    │ 57    │ housemaid   │ divorced │ basic.4y            │ no      │
⋮
│ 30

In [312]:
#changing target into float for model
datatest[!,:y] = convert.(Float64,datatest[!,:y])

30488-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0

In [313]:
#converting data into a matrix
datamatrix = convert(Matrix,datatest)

30488×20 Array{Any,2}:
 56  "housemaid"    "married"   …  93.994  -36.4  4.857  5191.0  0.0
 37  "services"     "married"      93.994  -36.4  4.857  5191.0  0.0
 40  "admin."       "married"      93.994  -36.4  4.857  5191.0  0.0
 56  "services"     "married"      93.994  -36.4  4.857  5191.0  0.0
 59  "admin."       "married"      93.994  -36.4  4.857  5191.0  0.0
 24  "technician"   "single"    …  93.994  -36.4  4.857  5191.0  0.0
 25  "services"     "single"       93.994  -36.4  4.857  5191.0  0.0
 25  "services"     "single"       93.994  -36.4  4.857  5191.0  0.0
 29  "blue-collar"  "single"       93.994  -36.4  4.857  5191.0  0.0
 57  "housemaid"    "divorced"     93.994  -36.4  4.857  5191.0  0.0
 35  "blue-collar"  "married"   …  93.994  -36.4  4.857  5191.0  0.0
 35  "blue-collar"  "married"      93.994  -36.4  4.857  5191.0  0.0
 50  "blue-collar"  "married"      93.994  -36.4  4.857  5191.0  0.0
  ⋮                             ⋱   ⋮                               
 38  "house

In [205]:
#iterating through matrix
size(datamatrix)[2]
for i = 1:(size(datamatrix)[2]-2)
    uniquee = unique(datamatrix[:,i])
    for j = 1:size(datamatrix)[1]
        for k = 1:size(uniquee)[1]
            if datamatrix[j,i] == uniquee[k]
                datamatrix[j,i] = Int(k)
            end
        end
    end
    println(i)
end

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [457]:
munet = datamatrix[:,end-4:end]

30488×5 Array{Any,2}:
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
  ⋮                               
 94.767  -50.8  1.031  4963.6  0.0
 94.767  -50.8  1.031  4963.6  0.0
 94.767  -50.8  1.031  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0

In [169]:
using Flux
using Statistics

using Flux.NNlib
using Flux: throttle, normalise
using Flux: binarycrossentropy
using Base.Iterators: repeated
using Flux: @epochs

In [458]:
munet

30488×5 Array{Any,2}:
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
 93.994  -36.4  4.857  5191.0  0.0
  ⋮                               
 94.767  -50.8  1.031  4963.6  0.0
 94.767  -50.8  1.031  4963.6  0.0
 94.767  -50.8  1.031  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  0.0
 94.767  -50.8  1.028  4963.6  1.0
 94.767  -50.8  1.028  4963.6  0.0

In [459]:
using NamedArrays
test = NamedArray(munet)

30488×5 Named Array{Any,2}
A ╲ B │      1       2       3       4       5
──────┼───────────────────────────────────────
1     │ 93.994   -36.4   4.857  5191.0     0.0
2     │ 93.994   -36.4   4.857  5191.0     0.0
3     │ 93.994   -36.4   4.857  5191.0     0.0
4     │ 93.994   -36.4   4.857  5191.0     0.0
5     │ 93.994   -36.4   4.857  5191.0     0.0
6     │ 93.994   -36.4   4.857  5191.0     0.0
7     │ 93.994   -36.4   4.857  5191.0     0.0
8     │ 93.994   -36.4   4.857  5191.0     0.0
9     │ 93.994   -36.4   4.857  5191.0     0.0
10    │ 93.994   -36.4   4.857  5191.0     0.0
11    │ 93.994   -36.4   4.857  5191.0     0.0
12    │ 93.994   -36.4   4.857  5191.0     0.0
⋮            ⋮       ⋮       ⋮       ⋮       ⋮
30477 │ 94.767   -50.8   1.031  4963.6     0.0
30478 │ 94.767   -50.8   1.031  4963.6     0.0
30479 │ 94.767   -50.8   1.031  4963.6     1.0
30480 │ 94.767   -50.8   1.028  4963.6     0.0
30481 │ 94.767   -50.8   1.028  4963.6     0.0
30482 │ 94.767   -50.8   1.028  4

In [460]:
#dividing features into X variable and and target into Y
X = convert(Array,munet[:,[:1,:2,:3,:4]]);

In [461]:
Y = convert(Array,munet[:,[:5]]);

In [462]:
X

30488×4 Array{Any,2}:
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
 93.994  -36.4  4.857  5191.0
  ⋮                          
 94.767  -50.8  1.031  4963.6
 94.767  -50.8  1.031  4963.6
 94.767  -50.8  1.031  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6
 94.767  -50.8  1.028  4963.6

In [463]:
Y

30488×1 Array{Any,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0

In [464]:
#converting Y set into float for training
datatest[!,:y] = convert.(Float64,datatest[!,:y])

30488-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 0.0
 0.0
 1.0
 0.0

In [465]:
num_tr_ex = length(Y);
num_tr_ex

30488

In [466]:
#naormalizing some features
X = (X .- mean(X, dims = [90,1])) ./ std(X, dims = [90,1]);

In [467]:
size(X), size(Y)

((30488, 4), (30488, 1))

In [488]:
#Here we build a model for Log Regression in flux
#param tells it what to train
W = param(zeros(2))
b = param([0.])

┌ Warning: `param(x)` is deprecated, use `x` instead.
│   caller = top-level scope at In[488]:1
└ @ Core In[488]:1
┌ Warning: `param(x)` is deprecated, use `x` instead.
│   caller = top-level scope at In[488]:4
└ @ Core In[488]:4


1-element Array{Float64,1}:
 0.0

In [480]:
#W is matrix of weight and b is bias
predict(x) = NNlib.σ.(x*W .+ b)

predict (generic function with 1 method)

In [439]:
#here we setup loss function
loss(x, y) = sum(binarycrossentropy.(predict(x), y))/num_tr_ex

loss (generic function with 1 method)

In [492]:
using Flux: Params
par = Params([W, b])

Params([[0.0, 0.0], [0.0]])

In [ ]:
#Here we using Stockastic descent with learning rate of 0.01
using Flux: Params
par = Params([W, b])
opt = SGD(par, 0.1; decay = 0)
evalcb() = @show(loss(X, Y))

In [ ]:
#here we train the model
cb = evalcb
datas = repeated((X, Y), 200)
Flux.train!(loss, datas, opt, cb)

In [491]:
#We test the accuracy
p = predict(x) .> 0.5
sum(p .== y) / length(Y)

0.8733928102860141

In [ ]:
predict([0 1])